[package]
name = "kb_difftool"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite ={version = "0.32.1", features = ["chrono"]}
iced ={ version = "0.13.1"}
tokio = {version =  "1", features = ["full"]}